import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "../context/Theme";
// import TopHeader from "@/components/Header/TopHeader";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair",
  display: "swap",
});

// const montserrat = Montserrat({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800", "900"],
//   variable: "--font-montserrat",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "SEKRA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body
          className={` ${playfair.variable} ${playfair.className} antialiased`}
        >
          {/* <TopHeader /> */}
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeContextProvider>
    </html>
  );
}
