import type { Metadata } from "next";
import { Meow_Script, Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import CartProvider from "@/context/CartContext";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";

const corinthia = Meow_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-corinthia",
  display: "swap",
});
const notoSans = Noto_Sans_Arabic({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["arabic"],
  variable: "--font-notoSans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "SEKRA",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // Validate locale
  if (!hasLocale(routing.locales, locale)) {
    console.log("locale wrong");
  }

  // Get messages for the locale
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${corinthia.variable} ${notoSans.variable} ${
          locale === "ar" ? "font-notoSans" : ""
        } antialiased light min-h-screen flex flex-col`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <SessionProvider>
            <CartProvider>
              <Header />
              <Toaster
                position="top-right"
                expand={false}
                offset={60}
                mobileOffset={60}
                duration={2000}
                invert
                theme="light"
              />
              <main className="flex-grow">{children}</main>
              <Footer />
            </CartProvider>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
